name: Publish to Confluence
description: Publishes content and attachments to Confluence.
author: 'Andreas Pfurtscheller'
branding:
  color: blue
  icon: book
inputs:
  url:
    description: 'Confluence url.'
    required: true
  username:
    description: 'Confluence username.'
    required: false
  password:
    description: 'Confluence password.'
    required: false
  access_token:
    description: 'Confluence access token.'
    required: false
  page_id:
    description: 'Confluence page id.'
    required: true
  attachments:
    description: 'List of attachments to publish.'
    required: false
  # TODO: support title
  # title:
  #   description: 'Title of the page to publish.'
  #   required: false
  # TODO: support content
  # content:
  #   description: 'Content to publish.'
  #   required: false
runs:
  using: 'node'
  main: 'dist/main/index.js'
